//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bingo_candidate")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub bingo: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub candidate: Uuid,
  pub position: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::bingo::Entity",
    from = "Column::Bingo",
    to = "super::bingo::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Bingo,
  #[sea_orm(
    belongs_to = "super::candidate::Entity",
    from = "Column::Candidate",
    to = "super::candidate::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Candidate,
}

impl Related<super::bingo::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Bingo.def()
  }
}

impl Related<super::candidate::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Candidate.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
