//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub mod prelude;

pub mod bingo;
pub mod bingo_candidate;
pub mod bingo_user;
pub mod candidate;
pub mod invalid_jwt;
pub mod key;
pub mod season;
pub mod user;
