//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "season")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub year: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::bingo::Entity")]
  Bingo,
  #[sea_orm(has_many = "super::candidate::Entity")]
  Candidate,
}

impl Related<super::bingo::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Bingo.def()
  }
}

impl Related<super::candidate::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Candidate.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
